#!/bin/bash
sudo apt-get update
sudo apt-get install git -y
cd /home/ubuntu
sudo git clone https://github.com/Shuvo-Hoque/DevOps-Challenge.git
cd /home/ubuntu/DevOps-Challenge
sudo chmod +x ./install.sh
sudo chmod +x ./install1.sh
sudo chmod +x ./install2.sh
sudo ./install.sh
sudo ./install1.sh
sudo ./install2.sh